version: "3"

services:

  rabbitmq:
    build: rabbitmq
    image: catapulte/rabbitmq
    environment:
    - "RABBITMQ_DEFAULT_USER=guest"
    - "RABBITMQ_DEFAULT_PASSWORD=guest"
    ports:
    - 1883:1883
    - 5672:5672
    - 15672:15672

  mongodb:
    build: mongodb
    image: catapulte/mongodb
    environment:
    - "MONGODB_USER=guest"
    - "MONGODB_PASS=guest"
    - "MONGODB_DATABASE=cat"
    ports:
    - 27017:27017
    volumes:
    - mongodata:/data/db

volumes:
  mongodata:
    driver: local
