version: "2"

services:

  rabbitmq:
    build: rabbitmq
    image: catapulte/rabbitmq
    environment:
    - "RABBITMQ_USER=lolcat"
    - "RABBITMQ_PASSWORD=lolcat"
    ports:
    - 1883:1883
    - 5672:5672
    - 15672:15672

  mongodb:
    build: mongodb
    image: catapulte/mongodb
    environment:
    - "MONGODB_USER=guest"
    - "MONGODB_PASS=guest"
    - "MONGODB_DATABASE=cat"
    ports:
    - 27017:27017
