- name: create lolcat user
  user: name=lolcat
        state=present

- file: path=/home/lolcat/.ssh
        state=directory
        mode=0700
        owner=lolcat
        group=lolcat

- name: add authorized keys
  authorized_key: user=lolcat
                  key={{ item }}
                  state=present
  with_file:
    - deploy_key.pub

- name: configure apps
  template: src=application.yml
            dest=/home/lolcat/application.yml
            owner=lolcat
            group=lolcat

- name: install api systemd units
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }}
  with_items:
  - simple-api.service
  - simple-api-update.service
  - simple-api-update.path
  - catinder-api.service
  - catinder-api-update.service
  - catinder-api-update.path
  - proximity-aggregator.service
  - proximity-aggregator-update.service
  - proximity-aggregator-update.path
  - lolcat-docker-backend.service
  register: units

- name: reload systemd units
  command: systemctl daemon-reload
  when: units.changed

- name: enable api services update monitors
  service: name={{ item }} enabled=yes
  with_items:
  - simple-api
  - simple-api-update.path
  - catinder-api
  - catinder-api-update.path
  - proximity-aggregator
  - proximity-aggregator-update.path

- name: clone docker backend compose file
  unarchive: src=https://github.com/catapulte/infra/archive/master.tar.gz dest=/home/lolcat remote_src=True

- name: start lolcat services
  service: name={{ item }} state=started enabled=yes
  with_items:
  - lolcat-docker-backend
  - simple-api
  - catinder-api
  - proximity-aggregator
