defaultEntryPoints = ["http", "https"]

[web]
address = ":8000"

[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
email = "lolcat@passoire.net"
storage = "acme.json"
entryPoint = "https"
onDemand = false
onHostRule = false

[[acme.domains]]
   main = "lolcat.passoire.net"
   sans = ["simple.lolcat.passoire.net", "catinder.lolcat.passoire.net"]

[file]

[backends]
  [backends.simpleapi]
    [backends.simpleapi.servers.server1]
    url = "http://localhost:8081"
  [backends.catinderapi]
    [backends.catinderapi.servers.server1]
    url = "http://localhost:8082"

[frontends]
  [frontends.simpleapi]
  backend = "simpleapi"
    [frontends.simpleapi.routes.test_1]
    rule = "Host:simple.lolcat.passoire.net"
  [frontends.catinderapi]
  backend = "catinderapi"
    [frontends.catinderapi.routes.test_1]
    rule = "Host:catinder.lolcat.passoire.net"
